includes:
  - base.yaml
model:
  model_name: LECIvGIN
ood:
  ood_alg: LECI
  ood_param: 0.0
  extra_param:
    - 0.01
    - 0
    - 0.1
    - 60
    - 0.01
    - true
train:
  max_epoch: 200
  lr: 0.001
  pre_train: 50
  weight_decay: 0.0
log_file: exp_0
clean_save: true
